source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'IPtProxyUI_Example' do
  platform :ios, '13.0'

  pod 'IPtProxyUI', :path => '../'

#  pod 'IPtProxy', :path => '../../IPtProxy'

  target 'IPtProxyUI_Tests' do
    inherit! :search_paths
  end
end

target 'IPtProxyUI_Mac_Example' do
  platform :osx, '11'

  pod 'IPtProxyUI', :path => '../'

#  pod 'IPtProxy', :path => '../../IPtProxy'
end
