use_frameworks!

target 'IPtProxyUI_Example' do
  platform :ios, '11.0'

  pod 'ReachabilitySwift', :git => 'https://github.com/tladesignz/Reachability.swift'
  pod 'MBProgressHUD', :git => 'https://github.com/threema-jarem/MBProgressHUD.git'
  pod 'IPtProxyUI', :path => '../'

  target 'IPtProxyUI_Tests' do
    inherit! :search_paths
  end
end

target 'IPtProxyUI_Mac_Example' do
  platform :osx, '11'

  pod 'IPtProxyUI', :path => '../'
end
